### ISSUE TITLE
Adding a Company starting with P

### ISSUE THREAD

**Issue by devchaos0** [OSCA-Ado-Ekiti/tech-companies-in-africa#101]

**Comment by nobledeveloper01** [comment]
I want to start editing and adding company starting with A and to D add company starting with P too

**Comment by Hazaloolu** [comment]
i would love to be assigned this task.

**Comment by Lumetech** [comment]
i would like to be assigned to this i have a few ideas of some letter "P" compainies

**Comment by Elijah699** [comment]
@Lumetech you can work  on this.

**Comment by lilmow** [comment]
I will like to work on it
