### ISSUE TITLE
Adding a company starting with K

### ISSUE THREAD

**Issue by devchaos0** [OSCA-Ado-Ekiti/tech-companies-in-africa#103]

**Comment by Victorayo** [comment]
Will love to work on this. Assign me this task @Chaos10001 @OSCA-Ado-Ekiti

**Comment by OSCA-Ado-Ekiti** [comment]
@Chaos10001 you can work on this

**Comment by OSCA-Ado-Ekiti** [comment]
@Chaos10001 you also created issue #102, kindly work on both issues and send in a single PR for both

**Comment by Victorayo** [comment]
> @Chaos10001 you also created issue #102, kindly work on both issues and send in a single PR for both

Alright will do send in the PR now

**Comment by Victorayo** [comment]
> > @Chaos10001 you also created issue #102, kindly work on both issues and send in a single PR for both
> 
> Alright will do send in the PR now

You can find the PR at #111

**Comment by devchaos0** [comment]
Alright
