### ISSUE TITLE
Company name change 

### ISSUE THREAD

**Issue by Timonwa** [OSCA-Ado-Ekiti/tech-companies-in-africa#11]
AbokiAfrica is now called Grey.
You can use "Grey(formally called AbokiAfrica)" instead and change the website too.

**Comment by saintmalik** [comment]
Nice catch 👍, can you help make this changes?

**Comment by Timonwa** [comment]
Sure. I will make the changes.

**Comment by OSCA-Ado-Ekiti** [comment]
Thank you for sending in the PR
