### ISSUE TITLE
Confirm the validity of the company "Wasoko"

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/tech-companies-in-africa#127]
The company information for Wasoko is incomplete. please verify the authencity of the company. If it still exists send a pr with the updated information else send a pr with it exclusion in the `techCompanies.js` and `README.md` file

**Comment by TomerPacific** [comment]
@gray-adeyi  - I'd like to help out here.

**Comment by TomerPacific** [comment]
@gray-adeyi  - I have opened a [PR](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/pull/144).
