### ISSUE TITLE
Move flutterwave company info from letter T section in the README.md

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/tech-companies-in-africa#128]
Currently Information on flutter wave is available in the `README.md` file in the companies that start with letter `T` section. Rename it from `TheFlutterwave` and move the to the letter `F` section

**Comment by Victorayo** [comment]
Assign me this task pls @gray-adeyi 


Solved in #132

**Comment by gray-adeyi** [comment]
@Victorayo you can fix this now

**Comment by Victorayo** [comment]
> @Victorayo you can fix this now

Done. It's in PR #139 and PR #138

@gray-adeyi @OSCA-Ado-Ekiti
