### ISSUE TITLE
Removing and replacing with right details for Opay in the tech companies.json file

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/tech-companies-in-africa#131]
Notice there is a duplicate of submission for Opay.
Olu is not the CEO anymore, moreover Zhou Yahuiis the founder
Will like to work on it.

Below are the screenshot to clear the doubt;

![Screenshot_20231004-141724](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/assets/53627044/7ce6abca-24c5-4755-854f-74dba034b34b)
![Screenshot_20231004-141646](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/assets/53627044/d7a1b3be-8455-4db7-affd-bdeb1f676c90)
![IMG-20231004-WA0009](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/assets/53627044/099347ba-b4cc-4f16-afe7-331d95b17f05)

**Comment by Victorayo** [comment]
Assign my this task pls @gray-adeyi @OSCA-Ado-Ekiti

**Comment by gray-adeyi** [comment]
That's amazing @Victorayo I'll assign this to you in a bit. I'm currently refactoring the project so it's easy to contribute to. I'll let you know when it's okay to go ahead

**Comment by Victorayo** [comment]
> That's amazing @Victorayo I'll assign this to you in a bit. I'm currently refactoring the project so it's easy to contribute to. I'll let you know when it's okay to go ahead

Can I still proceed with this or it has been sorted by you and other maintenars? @gray-adeyi

**Comment by gray-adeyi** [comment]
Yeah sure! you're good to go

**Comment by Victorayo** [comment]
> Yeah sure! you're good to go

Solution in PR #140 

@gray-adeyi @OSCA-Ado-Ekiti
