### ISSUE TITLE
Website link not working 

### ISSUE THREAD

**Issue by Timonwa** [OSCA-Ado-Ekiti/tech-companies-in-africa#15]
When I click on the web link, it takes me to a 404 page.
![20220326_075256](https://user-images.githubusercontent.com/63044364/160228523-60650377-cb4e-4e0d-bc2d-1342016363c4.jpg)

**Comment by OSCA-Ado-Ekiti** [comment]
Yeah, thanks nothing has been built on it yet, if you wanna pick it up,
it's cool

**Comment by Timonwa** [comment]
Ok. I can do that. I will create a new issue on it and work on it.

**Comment by OSCA-Ado-Ekiti** [comment]
Thanks for picking up this issue

**Comment by Timonwa** [comment]
Good day, all the names of the company and founders in the Json file are their twitter handles right? Also can I modify the Json file. I want to include the links to the websites in it so that one can click on the links to the website and twitter handles.

**Comment by OSCA-Ado-Ekiti** [comment]
Yeah, sure , you can go ahead and modify it😃, thank you for your
contribution

**Comment by Timonwa** [comment]
Cool, and you are welcome.
