### ISSUE TITLE
Adding more new  companies to the directory from A to Z 

### ISSUE THREAD

**Issue by diwuracreatives** [OSCA-Ado-Ekiti/tech-companies-in-africa#155]
Can we also add more information to the company card like company logo and date/year founded, I wok love to work on this feature thank you,

**Comment by Lumetech** [comment]
i would like to work on this issue

**Comment by Victorayo** [comment]
> Can we also add more information to the company card like company logo and date/year founded, I wok love to work on this feature thank you,

I think this issue title should be changed then to "add more information to the company card" instead of what's there currently.

Can pls change it for better clarity for other issues to be created?
Thanks

**Comment by lilmow** [comment]
I will like to work on the issue

**Comment by Elijah699** [comment]
@diwuracreatives are you still up for this?

**Comment by diwuracreatives** [comment]
Yes i am @Elijah699

**Comment by Elijah699** [comment]
@diwuracreatives you can go ahead to implement your suggestions.

Reach out to me if you need help.

**Comment by diwuracreatives** [comment]
ok will do that
