### ISSUE TITLE
Fix the search functionality of the website & add a search icon to the search input field

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/tech-companies-in-africa#179]
1. Assist us with fixing the site search functionality

2. As seen below, if anyone wants to search for any company, only placeholder was created, there isn't any search  🔍🔎 icon which the user can click to authorize/starting the engine search.

Anyone to do that? @OSCA-Ado-Ekiti  @gray-adeyi @Elijah699

![Screenshot_20231016-093622](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/assets/53627044/cbc3ef0f-e90d-4b5d-a1ed-2e86f41872b7)

**Comment by i-MMANTECH** [comment]
I can help

**Comment by OSCA-Ado-Ekiti** [comment]
@i-MMANTECH you can work on this

**Comment by OSCA-Ado-Ekiti** [comment]
@i-MMANTECH Are you still on this please?

**Comment by nobledeveloper01** [comment]
Assign me to this

**Comment by Elijah699** [comment]
@nobledeveloper01 kindly proceed.

**Comment by OSCA-Ado-Ekiti** [comment]
Thank you @nobledeveloper01 for completing this

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #266
