### ISSUE TITLE
Add africa tech startups or companies starting with V

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#20]
Research and find  africa startups/companies whose name starts with V and add them to the  [techCompanies.js ](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/blob/main/src/techCompanies.js) file

here is a format to follow;

    {
      "companyName": "Swift Finance",
      "companyTwitterHandle": "SwiftFinanceApp",
      "foundersTwitterHandle": ["dammieololade", "adeileri", "Anani_oluwatobi"],
      "industry": "SME Banking",
      "website": "https://www.swiftfinance.app"
    }

**Comment by Victorayo** [comment]
Can you now assign me this boss? 

You kuku ignore me for the last two request?  🙄

**Comment by JhayJahswiil** [comment]
Assign me

**Comment by Victorayo** [comment]
> Assign me

🧐🧐🧐

**Comment by Moyincodes** [comment]
Can you assign me?

**Comment by Victorayo** [comment]
Wish to work on this @OSCA-Ado-Ekiti

**Comment by OSCA-Ado-Ekiti** [comment]
@Victorayo you can work on it

**Comment by Victorayo** [comment]
> @Victorayo you can work on it

Alright boss. You can find the PR at #113 

I also added to the ReadME file. PR #112 


Kindly check both and merge
