### ISSUE TITLE
Add africa tech startups or companies starting with Z

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#21]
Research and find  africa startups/companies whose name starts with Z and add them to the  [techCompanies.js ](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/blob/main/src/techCompanies.js) file

here is a format to follow;

    {
      "companyName": "Swift Finance",
      "companyTwitterHandle": "SwiftFinanceApp",
      "foundersTwitterHandle": ["dammieololade", "adeileri", "Anani_oluwatobi"],
      "industry": "SME Banking",
      "website": "https://www.swiftfinance.app"
    }

**Comment by hamzabohra** [comment]
can i work on this?

**Comment by RuthChisom** [comment]
Hello, I'd love to work on this. Kindly add me as a collaborator. Thanks.

**Comment by JhayJahswiil** [comment]
can I work on this?

**Comment by OSCA-Ado-Ekiti** [comment]
> can I work on this?

yes

**Comment by OSCA-Ado-Ekiti** [comment]
> Hello, I'd love to work on this. Kindly add me as a collaborator. Thanks.

You can work on it too, you dont need th collaborator acess, you can easy fork the repo, create a branch and make your contribution, then send a PR, see this contributing guide: https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2022-Ekiti/blob/main/CONTRIBUTING.md

**Comment by metrosmash** [comment]
hi i would like to work on this

**Comment by Sproff** [comment]
@OSCA-Ado-Ekiti I've made a PR for this

**Comment by Victorayo** [comment]
Wish to work on this @OSCA-Ado-Ekiti
