### ISSUE TITLE
Add africa tech startups or companies starting with F

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#22]
Research and find  africa startups/companies whose name starts with F and add them to the [techCompanies.js ](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/blob/main/src/techCompanies.js) file

here is a format to follow;

    {
      "companyName": "Swift Finance",
      "companyTwitterHandle": "SwiftFinanceApp",
      "foundersTwitterHandle": ["dammieololade", "adeileri", "Anani_oluwatobi"],
      "industry": "SME Banking",
      "website": "https://www.swiftfinance.app"
    }

**Comment by Victorayo** [comment]
Assign me this pls

**Comment by OSCA-Ado-Ekiti** [comment]
> Assign me this pls

esoohhh pehhh 👀

**Comment by Victorayo** [comment]
> > Assign me this pls
> 
> esoohhh pehhh 👀

🤕🤕🤕 Me self never do 3 PRs not to talk of 4. Abeg, i don't want to be left behind 😭

**Comment by hamzabohra** [comment]
Can i work on this?

**Comment by OSCA-Ado-Ekiti** [comment]
sure @hamzabohra

**Comment by Sproff** [comment]
Will pick this up @OSCA-Ado-Ekiti

**Comment by OSCA-Ado-Ekiti** [comment]
> Will pick this up @OSCA-Ado-Ekiti

yes, you can

**Comment by Sproff** [comment]
PR - https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/pull/52

@OSCA-Ado-Ekiti
