### ISSUE TITLE
Update Startups/Companies Name or Founder

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#23]
Looking at the recent aqcuisition of Abeg by PiggyVest, we believe there has been some changes in company ownership, you can do some research and update the company details in the  [techCompanies.js ](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/blob/main/src/techCompanies.js) file

**Comment by SlimmyTee** [comment]
Assign me

**Comment by Victorayo** [comment]
Assign me this pls

**Comment by OSCA-Ado-Ekiti** [comment]
> Assign me this pls

enihh peehhh 👀

**Comment by metrosmash** [comment]
Hi i would like to work on this pls assign me

**Comment by OSCA-Ado-Ekiti** [comment]
@metrosmash you can work on it, just add more startups to the techCompanies.js file
