### ISSUE TITLE
Remove Abegapp and 54gene

### ISSUE THREAD

**Issue by ezinneanne** [OSCA-Ado-Ekiti/tech-companies-in-africa#261]
Remove Abegapp since it has been rebranded to Pocketapp by Piggyvest. Also, remove 54gene

**Comment by ezinneanne** [comment]
Kindly assign me to this

**Comment by OSCA-Ado-Ekiti** [comment]
@ezinneanne Thank you for checking through the list and you can proceed with the correction please.

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #262
