### ISSUE TITLE
Add contents from techCompanies.json to techCompanies.js

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#35]
There are alot of companies that were added to techCompanies.js, but are missing in the [techCompanies.js ](https://github.com/OSCA-Ado-Ekiti/tech-companies-in-africa/blob/main/src/techCompanies.js) file, techCompanies is the file that is been rendered via the Frontend.

**Comment by JawHawk** [comment]
I can work on this, assign me pls

**Comment by OSCA-Ado-Ekiti** [comment]
assigned

**Comment by Elijah699** [comment]
Is this still open? @OSCA-Ado-Ekiti

**Comment by OSCA-Ado-Ekiti** [comment]
yes

**Comment by Sproff** [comment]
I've fixed the issue
@OSCA-Ado-Ekiti

**Comment by Elijah699** [comment]
@Sproff my 4PR plan in the mud 😔

**Comment by Sproff** [comment]
> @Sproff my 4PR plan in the mud 😔

Haha, sorry man😂

**Comment by Elijah699** [comment]
🤝🙌
