### ISSUE TITLE
Correcting Syntax errors in techCompanies.json file

### ISSUE THREAD

**Issue by Victorayo** [OSCA-Ado-Ekiti/tech-companies-in-africa#44]
There are some errors detected in the techCompanies.json file

- Indentation issue on the helium company added.
- incomplete details on the Vodacom company added.

**Comment by Victorayo** [comment]
Assign me this @OSCA-Ado-Ekiti

**Comment by Sproff** [comment]
@OSCA-Ado-Ekiti this issue might need to be closed because the file has been deleted.
