### ISSUE TITLE
Design: Revamping the the design

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/tech-companies-in-africa#51]
Revamping and redesigning the tech companies in africa, so it will include more details like active startups and dead startups, ability to filter with niche and more

**Comment by codesmith25103** [comment]
I want to work on this issue. Please assign me this issue

**Comment by OSCA-Ado-Ekiti** [comment]
assigned

**Comment by OSCA-Ado-Ekiti** [comment]
hello @codesmith25103 , please sync with @Sproff for more info on how to go about the issue
